---
language: go
go:
  - 1.7
  - 1.8
  - 1.9
env:
  - DEP_VERSION="0.3.2"

before_install:
  - go get -u golang.org/x/tools/cmd/goimports
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure
  - dep prune

script:
  - goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")
  - go tool vet $(find . -type f -name '*.go' -not -path "./vendor/*")
